# Generated by Django 3.2.18 on 2023-05-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
