# Generated by Django 4.2.1 on 2023-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoappmodel',
            options={'ordering': ['-updated', '-due_datetime']},
        ),
        migrations.AddField(
            model_name='todoappmodel',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
