# Generated by Django 4.2.1 on 2023-06-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_completed_time_todoappmodel_completed_on_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoappmodel',
            options={'ordering': ['completed', '-due_datetime', '-updated']},
        ),
    ]
