# Generated by Django 4.2.1 on 2023-06-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoappmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoappmodel',
            options={'ordering': ['completed', 'due_datetime', 'updated']},
        ),
    ]
