# Generated by Django 4.2.1 on 2023-06-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todoappmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoappmodel',
            options={'ordering': ['completed', 'due_datetime', 'updated_at_datetime']},
        ),
        migrations.RenameField(
            model_name='todoappmodel',
            old_name='created',
            new_name='created_at_datetime',
        ),
        migrations.RenameField(
            model_name='todoappmodel',
            old_name='updated',
            new_name='updated_at_datetime',
        ),
    ]
